### ISSUE TITLE
Sample output violates the spec

### ISSUE THREAD

**Issue by karagog** [opencomputeproject/ocp-diag-python#12]
One of the examples in the sample output violates the spec IMO. https://github.com/opencomputeproject/ocp-diag-core-python/blob/dev/examples/sample_output.txt#L59 shows that the extension content can be an arbitrary string value, but the spec says that this must be a JSON object.

Can we get clarification on whether this is valid results output, and/or update the example to show valid output?

**Comment by mimir-d** [comment]
You are absolutely correct, and this was also discovered recently in writing the rust api. I'll fix this and add the schema validator check for the examples here (which is how the rust one was highlighted)

**Comment by mimir-d** [comment]
> add the schema validator check for the examples here

actually now i see this was already in #5

**Comment by mimir-d** [comment]
fixed in #14
